import { useState, useEffect, useMemo } from 'react';
import type { Song, SongListState, SortField } from '@/types/song';
import { SAMPLE_SONGS } from '@/data/sample-songs';

export function useSongs() {
  const [state, setState] = useState<SongListState>({
    songs: [],
    isLoading: true,
    error: null,
  });
  const [sortField, setSortField] = useState<SortField>('artist');

  useEffect(() => {
    let cancelled = false;

    async function loadSongs() {
      try {
        // Try to load songs.json (generated by data pipeline)
        const module = await import('@/data/songs.json');
        const songs = module.default as Song[];

        if (!cancelled) {
          setState({
            songs: songs.length > 0 ? songs : SAMPLE_SONGS,
            isLoading: false,
            error: null,
          });
        }
      } catch {
        // Fallback to sample data
        if (!cancelled) {
          setState({
            songs: SAMPLE_SONGS,
            isLoading: false,
            error: null,
          });
        }
      }
    }

    loadSongs();
    return () => {
      cancelled = true;
    };
  }, []);

  const sortedSongs = useMemo(() => {
    return [...state.songs].sort((a, b) => {
      const fieldA = a[sortField].toLowerCase();
      const fieldB = b[sortField].toLowerCase();
      return fieldA.localeCompare(fieldB, 'pl');
    });
  }, [state.songs, sortField]);

  return {
    songs: sortedSongs,
    isLoading: state.isLoading,
    error: state.error,
    totalCount: state.songs.length,
    sortField,
    setSortField,
  };
}
